name: Instagram Scraper

on:
  workflow_dispatch:       # lets you run manually from GitHub

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright python-dotenv
          playwright install chromium

      - name: Run script
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python instagram-data.py

      - name: Upload challenge screenshot (if it exists)
        if: success() || failure()  # Run even if the script fails
        uses: actions/upload-artifact@v4
        with:
          name: challenge-screenshot
          path: challenge.png
          if-no-files-found: ignore